Ev/feat/implement docker image
NerdyNomads/Text-Savvy pull request #107
Opened 2022-03-21 20:41 UTC by valetee

## What does this PR do?

Add a GitHub action to build a Docker image and push it to Docker automatically

### Screenshots (optional)

### Steps to test/review (optional)

## Checklist before merging
- [ ] Applied options on the right:
      - Reviewers
      - Assignee
      - Labels
      - Project
      - Milestone
      - Linked Issues
- [ ] All linter rules passed
- [ ] Auto-build success

2022-03-21 22:05 UTC, deleonkf requested changes

2022-03-21 22:05 UTC, deleonkf commented on docker-compose.yml
> +      MONGODB_URI: mongodb+srv://textSavvyUser:nerdyNomads4350@textsavvy.cgzhf.mongodb.net/textSavvyDB?retryWrites=true&w=majority
We have a secret key that we can use for this, it's named `MONGO_URI` (used it for CI stuff)

2022-03-22 01:45 UTC, mariellemanlulu commented
Thanks!

--Approving after @deleonkf request has been added.

2022-03-22 21:39 UTC, mariellemanlulu approved these changes

2022-03-24 03:32 UTC, deleonkf approved these changes
beautiful

2022-03-24 03:33 UTC, merged