Re/feat/extension workspace
NerdyNomads/Text-Savvy pull request #95
Opened 2022-03-15 03:55 UTC by r3ym3l

## What does this PR do?
Chrome context menu displays workspace from database. Highlight and save text is saved on to the workspace **texts** array and the workspace ID is also attached to the saved text.

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/72952442/158299073-960e54d5-f474-43e6-a676-670e95038054.png)

### Steps to test/review (optional)
- start back-end (front-end optional)
- build the extension and load into chrome browser
- highlight and save while checking the database to see changes: 
    - workspace ID where text was saved is included
    - new text is pushed on to the workspace it was saved in

## Checklist before merging
- [ ] Applied options on the right:
      - Reviewers
      - Assignee
      - Labels
      - Project
      - Milestone
      - Linked Issues
- [ ] All linter rules passed
- [ ] Auto-build success

2022-03-20 01:16 UTC, mariellemanlulu requested changes

2022-03-20 01:16 UTC, mariellemanlulu commented on back-end/persistence/models/workspaces.model.js
> +        type: String
required?

2022-03-20 01:16 UTC, mariellemanlulu commented on back-end/persistence/models/workspaces.model.js
>      collaborators: {
by default maybe add the owner here to?

2022-03-20 01:16 UTC, mariellemanlulu commented on front-end/public/background.js
> +  // fetch(`${serverAddr}/accounts`)
we can remove this if we don't need it anymore

2022-03-20 01:16 UTC, mariellemanlulu commented on front-end/public/background.js
> +    fetch(`${serverAddr}/workspaces`)
we should break this down into multiple function? it's getting bigger.

2022-03-20 01:16 UTC, mariellemanlulu commented on front-end/src/organisms/Sidebar.js
> +  // FAKE DB FOR UI
if we don't need this, we can remove it.

2022-03-20 01:18 UTC, mariellemanlulu commented on front-end/public/background.js
> +    fetch(`${serverAddr}/workspaces`)
we can leave this in another branch if we need this branch merged right away

2022-03-20 01:18 UTC, deleonkf requested changes

2022-03-21 22:14 UTC, deleonkf reviewed
ty for fixing the tests! Might have missed committing the changes for `background.js` and `helper.js`

2022-03-21 23:56 UTC, deleonkf approved these changes

2022-03-22 01:32 UTC, mariellemanlulu approved these changes

2022-03-22 01:32 UTC, merged